### ISSUE TITLE
Failed to activate the autocomplete-R package

### ISSUE THREAD

**Issue by bryansims** [guillaumechaumet/autocomplete-R#7]
[Enter steps to reproduce:]

1. Go to install packages in Atom
2.Try to download autocomplete-R

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: [autocomplete-R](https://github.com/guillaumechaumet/autocomplete-R) package 0.6.0

### Stack Trace

Failed to activate the autocomplete-R package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1175864)
    at CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1176832)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:161712)
    at Object.consumeProvider_2 (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:161410)
    at Provider.t.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1029702)
    at ServiceHub.t.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2934590)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2942776)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2939831)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2939155)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2936786)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2939015)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2938958)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382643)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:899185
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:893791)
    at o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1032609)
    at ChildProcess.n.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1032815)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -6:32.2.0 core:paste (input.hidden-input)
     -6:30.4.0 core:move-up (input.hidden-input)
     -6:29.3.0 editor:select-to-end-of-line (input.hidden-input)
     -6:28.6.0 hydrogen:run (input.hidden-input)
     -6:28.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -6:12.9.0 core:copy (input.hidden-input)
  6x -3:52 datatip:toggle (input.hidden-input)
     -3:45.9.0 hydrogen:restart-kernel (input.hidden-input)
     -3:45.5.0 datatip:toggle (input.hidden-input)
     -1:07.2.0 core:move-right (input.hidden-input)
     -1:06.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:05.5.0 hydrogen:run (input.hidden-input)
     -1:05.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:51.3.0 hydrogen:restart-kernel (input.hidden-input)
     -0:51.1.0 datatip:toggle (input.hidden-input)
     -0:32.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.13.0 
autocomplete-python 1.11.0 
autocomplete-R 0.6.0 
Hydrogen 2.7.0 
hydrogen-launcher 1.2.2 
ide-python 1.2.0 
ide-r 0.1.8 
kite 0.138.0 
platformio-ide-terminal 2.8.4 
rbox 0.5.0 
```

**Comment by jfernandz** [comment]
I'm having the same issue.

This is my report

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: "Arch Linux"
**Thrown From**: [autocomplete-R](https://github.com/guillaumechaumet/autocomplete-R) package 0.6.0


### Stack Trace

Failed to activate the autocomplete-R package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/share/atom/resources/app/static/<embedded>:11:1210129)
    at CompositeDisposable.add (/usr/share/atom/resources/app/static/<embedded>:11:1211097)
    at Object.consumeProvider (/usr/share/atom/resources/app/static/<embedded>:11:162220)
    at Object.consumeProvider_2 (/usr/share/atom/resources/app/static/<embedded>:11:161918)
    at Provider.t.exports.Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1116456)
    at ServiceHub.t.exports.ServiceHub.provide (/usr/share/atom/resources/app/static/<embedded>:11:3411524)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:3419710)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3416765)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3416089)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3413720)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3415949)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3415892)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:381112)
    at /usr/share/atom/resources/app/static/<embedded>:11:934678
    at r (/usr/share/atom/resources/app/static/<embedded>:11:929284)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1119363)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1119517)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1118119)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-language-r 1.4.8 
atom-python-run 0.9.7 
atom-runner 2.7.1 
autocomplete-font-awesome 1.0.2 
autocomplete-latex 0.9.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.14.1 
autocomplete-R 0.6.0 
browser-plus 0.0.98 
browser-plus-open-new-window 0.0.1 
browser-plus-zoom 0.0.2 
build 0.70.0 
build-rscript 0.6.2 
busy-signal 2.0.1 
cobalt2-syntax 0.5.3 
color-picker 2.3.0 
dark-flat-ui 1.2.4 
file-icons 2.1.33 
git-log 0.4.1 
git-plus 8.7.0 
git-time-machine 2.1.0 
glacier-dark-ui 1.5.0 
hacking-the-kernel 1.7.4 
hacking-the-kernel-ui 1.8.5 
highlight-line 0.12.0 
highlight-selected 0.16.0 
Hydrogen 2.9.0 
ide-python 1.4.1 
ide-r 0.1.8 
intentions 1.1.5 
jumpy 5.0.2 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-completions 0.3.6 
linter 2.3.0 
linter-latex 1.0.0 
linter-lintr 1.2.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
markdown-preview-plus 3.8.1 
markdown-table-editor 1.1.2 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-autohider 1.6.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-titles 1.15.0 
multi-cursor 2.1.5 
outlander-syntax 2.0.0 
outlander-ui 1.4.0 
pdf-view 0.71.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
python-debugger 0.2.0 
python-indent 1.2.3 
python-tools 0.6.9 
snow-dark-syntax 0.1.1 
split-diff 1.6.0 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
sync-settings 0.8.6 
toggle-docks 0.1.0 
wakatime 7.1.1 
```

**Comment by jfernandz** [comment]
I think it would be fine @guillaumechaumet or @Andryas give us an idea about what could be causing this in order to try a fix.

I don't know if this is really related with this provider or with `autocomplete-plus` itself but I cannot get the suggestions deployment in `*.r` files, however it is working for `*.html` files, for instance.

I've solved the issue by disabling and enabling again `autocomplete-plus` or at least apparently is already fixed, I'll keep informing in the case it does appear again.

**Comment by guillaumechaumet** [comment]
Hi,
I don't use atom nor github so I have transfer the ownership to @WyRe 
Best,

**Comment by jfernandz** [comment]
@guillaumechaumet lol, I don't have idea about CoffeeScript or atom packages integration! :S

I would need a kind of docu or references to learn it

**Comment by guillaumechaumet** [comment]
Here https://atom.io/docs
